#!/bin/bash
# 
#                       [UP]
# A ping script to check if a server connection is up.
# No icmp info is displayed, just if the domain/IP is resolving.
#
#
target=$1
count=$( ping -c 1 $target | grep icmp* | wc -l )
if [ $count -eq 0 ]
# echo is spaced to print just off the edge of terminal window for easy reading.
# Change echo to whatever you like :)
then
        echo -e "\n\e[1;91m           Link DOWN\e[0m\n"
else
        echo -e "\n\e[1;32m           Link ACTIVE\e[0m\n"
fi
