#!/bin/bash

# WATCHTOWER cron script for checking lan connectivity
# Checks ping and performs "service network restart" if ping fails.
# Ping count is set aggressively to 2, Having ping set at anything less can cause false positives and send you into a network restart loop


PING_COUNT=2

PING="/bin/ping"

#Find the gateway IP address
GATEWAY_IP='ip route | grep default | cut -d " " -f 3'

# ping test
$PING -n -c "$PING_COUNT" "$GATEWAY_IP" &>/dev/null

if [ "$?" -ge 1 ]
then
    # This will log a message in system log.
    logger "Network access DOWN"
    service network restart
else
    logger "Network access OK"
fi